services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"  # OTLP gRPC endpoint
    networks:
      - otel-network
    depends_on:
      clickhouse:
        condition: service_healthy

  telemetrygen:
    build:
      context: tracegen
      dockerfile: Dockerfile
    environment:
      # Connection settings
      - OTLP_ENDPOINT=otel-collector:4317
      - OTLP_INSECURE=true
      - SERVICE_NAME=demo-service
      
      # Trace generation parameters
      - WORKERS=1
      - TRACES_PER_WORKER=5
      - RATE=5
      - CHILD_SPANS=2
      - SPAN_DURATION=10ms
      - STATUS_CODE=0
      
      # Runtime settings
      - RUN_INTERVAL=30      # Run every 30 seconds
      - RUN_COUNT=0          # Run indefinitely (0 = forever)
      - ENABLE_BATCH=true
      
      # Randomization settings
      - RANDOMIZE_CHILD_SPANS=true
      - MIN_CHILD_SPANS=1
      - MAX_CHILD_SPANS=5
      - RANDOMIZE_SPAN_DURATION=true
      - MIN_SPAN_DURATION=10
      - MAX_SPAN_DURATION=200
      
      # Optional custom attributes (uncomment if needed)
      # - CUSTOM_ATTRIBUTES=env=\"demo\",region=\"us-east-1\"
      
      # Verbosity level (1=verbose, 0=quiet)
      - VERBOSE=1
    restart: always
    networks:
      - otel-network
    depends_on:
      - otel-collector

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native TCP interface
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - otel-network
    healthcheck:
      test: ["CMD", "clickhouse-client", "--user", "default", "--password", "password", "--query", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  clickhouse_data:

networks:
  otel-network:
    driver: bridge