receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"   # Bind to all interfaces
      http:
        endpoint: "0.0.0.0:4318"   # Bind to all interfaces

exporters:
  qryn:
    # DSN using the native TCP protocol to connect to ClickHouse,
    # targeting database "otel" with provided credentials.
    dsn: "tcp://clickhouse:9000/otel?username=default&password=password"
    timeout: 10s
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [qryn]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [qryn]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [qryn]
